### ISSUE TITLE
希望添加昵称功能

### ISSUE THREAD

**Issue by otae-1204** [zhaomaoniu/nonebot-plugin-steam-info#13]
rt

**Comment by otae-1204** [comment]
11

**Comment by zhaomaoniu** [comment]
请将插件更新至 [v1.1.0](https://github.com/zhaomaoniu/nonebot-plugin-steam-info/releases/tag/v1.1.0) 并使用 `steamnickname [昵称]` 或 `steam昵称 [昵称]` 命令以添加昵称
