### ISSUE TITLE
期望添加群白名单功能

### ISSUE THREAD

**Issue by TsukimoriRin** [zhaomaoniu/nonebot-plugin-steam-info#14]
希望大大能添加一个能够在.env配置文件里面设置群里开启白名单功能 比如有些群开启播报 有些群关闭播报但是可以绑定steam

**Comment by TsukimoriRin** [comment]
还有就是有些群想开这个播报 有些群不想开但是 这个播报好像是全局开关的

**Comment by zhaomaoniu** [comment]
1. 关于播报开关: 经测试，播报开关是分群控制的，一个群的关闭不会影响另一个群。你可以提供一下你的环境信息(适配器、适配器版本、协议端等)吗？

2. 关于配置文件的白名单: 插件已经提供了开启/关闭播报的命令供用户使用，如果再添加一个位于配置文件中的白名单，会略显凌乱。你的表述不太清楚，我不明白再配置一个白名单有什么作用。

**Comment by TsukimoriRin** [comment]
抱歉！！！！ 因为我未经测试就提出问题 我这边试了下 bot在新加入群的时候是会默认开启这个功能的 导致我以为这个开启播报是不分群全局开启的
