### ISSUE TITLE
无法自动获取Steam用户状态

### ISSUE THREAD

**Issue by ZihuaGaoCHN** [zhaomaoniu/nonebot-plugin-steam-info#19]
运行时报错
[WARNING] nonebot_plugin_steam_info | API key (API Key) failed to get steam users info.
[ERROR] nonebot_plugin_steam_info | All API keys failed to get steam users info.
导致无法自动获取状态，以及播报
但是使用/steamcheck可以正常查看状态
网络代理已经设置，无论是路由器挂代理还是电脑本地运行代理都不行

**Comment by zhaomaoniu** [comment]
这是调用 API 次数太多后被限制导致的，请尝试调低 STEAM_REQUEST_INTERVAL 或配置更多的 API Key。

使用 steamcheck 查看状态时，插件会进行错误处理，fallback 到了缓存的状态上，因此可以正常查看。
