### ISSUE TITLE
【bug】发送steam信息报错

### ISSUE THREAD

**Issue by billyosoror** [zhaomaoniu/nonebot-plugin-steam-info#25]
python版本：3.11.9
版本：1.3.2
![捕获](https://github.com/user-attachments/assets/5adb25e0-50ab-4319-98cc-1003e433adf5)

**Comment by zhaomaoniu** [comment]
请更新至 [v1.3.3](https://github.com/zhaomaoniu/nonebot-plugin-steam-info/releases/tag/v1.3.3) 后重试
