### ISSUE TITLE
FeatureRequest:游玩中的游戏添加一个排序（类似1-N,A-z）的排序

### ISSUE THREAD

**Issue by sansenhoshi** [zhaomaoniu/nonebot-plugin-steam-info#9]
#### 给游戏中的玩家的游戏名称做一个排序，使其游玩相同游戏的玩家能排在一起：

这里我添加了一个sorted()方法，测试了一下，排序好像会耗费一些时间，如果您有更好的解决办法，可以试试

![](https://file.sansenhoshi.top/clu-images/20240515/97543e130d4c403d5724aae78a935276-B7313DDA-717F-4F16-96F7-E58EA62DBAD7.png)

#### 大致的效果图：

游玩的游戏会按照一个1-n/A-z的顺序排列，游玩相同游戏的人也会排在一起

![](https://file.sansenhoshi.top/clu-images/20240515/20240515165452-53BFABD0-A653-4F01-A344-0AE5609D6A30.png)

**Comment by zhaomaoniu** [comment]
这段排序看起来不太可能耗费太多时间

方便的话，麻烦直接 Pull Requests，不方便我就周末自己加了

**Comment by sansenhoshi** [comment]
我这边没拉取项目，我直接在文件里面改的，还有一些其他的自己的改动，不太方便，就麻烦你啦，后面我如果有好的想法和改动会提PR的

**Comment by zhaomaoniu** [comment]
已在 [v1.0.0](https://github.com/zhaomaoniu/nonebot-plugin-steam-info/releases/tag/v1.0.0) 支持按照字母表顺序排序游戏玩家
